http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  logsEndpoint:
    host: localhost
    paths: '/listar/logs*'
  galponEndponit:
    host: localhost
    paths: '/listar/muestras*'
serviceEndpoints:
  logservice:
     url: 'http://localhost:9000'
  galponservice:
     url:  'http://localhost:6000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
 logsPipeline:
      apiEndpoints:
        - logsEndpoint
      policies:
        - proxy:
            - action:
                serviceEndpoint: logservice
                changeOrigin: true
 galponPipeline:
      apiEndpoints:
        - galponEndpoint
      policies:
        - proxy:
            - action:
                serviceEndpoint: galponservice
                changeOrigin: true
