http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  logsEndpoint:
    host: localhost
    paths: '/listar/logs*'
serviceEndpoints:
  logservice:
     url: 'http://localhost:9000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
 logsPipeline:
      apiEndpoints:
        - logsEndpoint
      policies:
        - proxy:
            - action:
                serviceEndpoint: logservice
                changeOrigin: true
