version: '3'
services: 
    mongo:
      container_name: databse-mongodb-ms2 
      image: mongo
      ports:
          - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      volumes:
        - ./data:/data/mongodb
    mongo-express:
        container_name: mongo-express-ms2 
        image: mongo-express
        depends_on: 
          - mongo
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: root
    api:
       build: .
       ports: 
        - 7000:7000
    